name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Build NDS
    runs-on: ubuntu-latest
    container:
      image: aleixmt/bmde-linux:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Build
        run: |
          make

      - name: Upload NDS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-nds.nds
          path: hello-world-nds.nds

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download NDS Artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-world-nds.nds

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: hello-world-nds.nds
          tag: v1.0
          name: "Release v1.0"
          body: "Automated release of version v1.0"
          allowUpdates: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}